# Generated by Django 3.0.7 on 2020-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201205_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('OrderId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
