# Generated by Django 3.1.3 on 2021-01-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201217_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderid',
            name='time_st',
        ),
    ]
