# Generated by Django 3.0.7 on 2021-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_userorderid_time_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DId', models.IntegerField(max_length=200)),
                ('DName', models.CharField(max_length=200)),
                ('DMobile', models.IntegerField(max_length=10)),
                ('DPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
