# Generated by Django 3.0.7 on 2021-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_deliverypersondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypersondata',
            name='DId',
            field=models.IntegerField(),
        ),
    ]
