# Generated by Django 3.0.7 on 2021-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210411_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypersondata',
            name='DMobile',
            field=models.IntegerField(),
        ),
    ]
